# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.eFriendsHA: debug

# debugpy:

sensor:
  - platform: eFriendsHA
    ip: '192.168.178.41'
    apikey: !secret efriendsapi
